core/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls', namespace='student'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path
from student.views import list_apprentice, summary_assitance, get_into, record_assitance

app_name = 'student'

urlpatterns = [
  path('get_into/', get_into, name='get_into'),
  path('summary/<int:pk>/<str:tm>', summary_assitance, name='summary_assitance'),
  path('list/', list_apprentice, name='list_apprentice'),
  path('record/', record_assitance, name='record_assitance'),
]

student/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.core.validators import RegexValidator

class Apprentice(models.Model):
  id_app = models.AutoField(primary_key=True)
  name = models.CharField(_("Nombres"), max_length=100, help_text="Debe de ingresar sus nombres completos")
  surname = models.CharField(_("Apellidos"), max_length=200, help_text="Ingrese sus apellidos completos")
  dni_regex = RegexValidator(regex=r'^\+?1?\d{8}', message = ("Debe de ingresar los 8 digitos de DNI"))
  dni_est = models.CharField( validators=[dni_regex], max_length=8, unique=True)
  created_at = models.DateTimeField(_("Creado"), auto_now_add=True)
  updated_at = models.DateTimeField(_("Actualizado"), auto_now=True)
  
  def __str__(self):
    return str(self.name)
  
class Assistance(models.Model):
  id_ass = models.AutoField(primary_key=True)
  apprentice = models.ForeignKey(Apprentice, verbose_name=_("Aprendis"), on_delete=models.CASCADE)
  entry_boolean = models.BooleanField(default=False)
  entry_at = models.DateTimeField(_("Hora de Ingreso"), blank=True, null=True)
  exit_boolean = models.BooleanField(default=False)
  exit_at = models.DateTimeField(_("Hora de Salida"), blank=True, null=True)
  
  def __str__(self):
    return str(self.apprentice)

student/forms.py
from django import forms
from .models import Assistance

class AssistanceForm(forms.ModelForm):
  class Meta:
    model =Assistance
    fields = "__all__"

core/views.py
from django.shortcuts import render

def index(request):

  return render(request, "index.html")

student/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_list_or_404
from student.models import Apprentice, Assistance
from datetime import datetime
from student.forms import AssistanceForm
from datetime import datetime


def get_into(request):
  if request.method == 'POST':
    asst = AssistanceForm(request.POST or None, request.FILES or None)
    id = request.POST['apprentice']
    id_asst = Apprentice.objects.get(pk=id)
    if request.session.test_cookie_worked():
      print("sfjsdfksñdfsdsjk")
      request.session.delete_test_cookie()
    if asst.is_valid():
      data = asst.save(commit=False)
      data.apprentice = id_asst
      data.entry_boolean = True
      data.exit_boolean = False
      data.save()
      print("To save")
      return HttpResponseRedirect(reverse('student:list_apprentice',))
  else:
    forms = AssistanceForm(request.POST or None, request.FILES or None)
  # try

    
  #   if request.method == "POST":
  #     id = request.POST['idcode']
  #     print("Numero de id: ",id)
  #     userid = Apprentice.objects.get(pk=id)
  #     print("sisisiisis")
  #     


        # Apprentice.entry_boolean = request.POST['entry_boolean', True]


  # except Apprentice.DoesNotExist:
  #   print("No existe")

  context ={
    'title': 'Ingresar INGRESO',
    
    }

  return render(request, 'student/get_into.html', context)


def list_apprentice(request):
  print("List de Aprendices")
  # if request.method == "POST":
  #   id = request.POST.getlist('assitance[]')
  #   print("Numero de id: ",id)
  #   return render(request, 'student/summary.html',)
    # id_asst = Assistance.objects.get(pk=id)
    # print("La salida es :", id_asst.exit_boolean)

  ass = Assistance.objects.all()

  context ={
    'title': "Lista",
    'ass' : ass,
  }
  return render(request, 'student/list.html', context)


def summary_assitance(request,pk,tm):
#Una persona cuenta con un DNI, debe ser registrado su ingreso y salida.
#Se realiza la busqueda la ultima vez que ingreso y que todavia no se registro su salida  
#Se tiene la busqueda pk de aprentice la entry_at
#Se debe de grabar summary
  app = Assistance.objects.filter(apprentice__id_app=pk,entry_at=tm,exit_boolean=False)
  time_now= datetime.now()
  
  print(time_now)
  ass_id = Assistance.objects.get(pk=app[0].id_ass)

  print(ass_id.id_ass)
  if request.method == "POST":
    ass_id.exit_boolean = True
    ass_id.exit_at = time_now
    ass_id.save(update_fields=['exit_boolean','exit_at'])
    print("se grabo")
    return HttpResponseRedirect(reverse('student:record_assitance',))
    

  #id_asst = Apprentice.objects.get(pk=int(ass_id.id_ass))

    # id_asst = Assistance.objects.get(pk=id)
    # print("La salida es :", id_asst.exit_boolean)
    # time_now = datetime.now()
    # print(time_now)
    
  print(ass_id)
  context ={
    'ass_id':ass_id,
    'title': 'Resumen',
    }
  return render(request, 'student/summary.html', context)


def record_assitance(request):

  asst = Assistance.objects.filter(entry_boolean=True, exit_boolean=True)
  days_times_total =[]
  for n in asst:
    app_1 = Assistance.objects.get(pk=n.id_ass)
    
    day_time_entry = app_1.entry_at.strftime('%y%m%d %H:%M:%S')
    day_time_exit = app_1.exit_at.strftime('%y%m%d %H:%M:%S')

    formato = '%y%m%d %H:%M:%S'
    day_time = datetime.strptime(day_time_exit, formato) - datetime.strptime(day_time_entry, formato)
    
    days_times_total.append(day_time)
    

  asst_time = zip(asst,days_times_total)
  context ={
    'title': "Historial",
    'asst_time' : asst_time,
  }
  return render(request, 'student/record.html', context)

student/templates/student/get_into.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
  <link rel="stylesheet" href="{% static 'student/clock.css' %}">
{% endblock css %}
  

{% block scripts %}
  <script src="{% static 'student/clock.js' %}" defer></script>
{% endblock scripts %}


{% block title %}
  {{title}}
{% endblock title %}


{% block content %}
  <h1 class="text-center">{{title}}</h1>

  <div class="reloj mb-5" id="relojnumerico" onload="cargarReloj()"></div>

  <div class="d-flex flex-column min-vh-10 justify-content-center align-items-center" id="template-bg-5">
    <div class="card mb-1 p-5 bg-dark bg-gradient text-white col-md-4">
      <div class="card-header text-center">
        <h3>Iniciar sesión </h3>
      </div>
      <div class="card-body mt-3">
        <form action="" method="POST">
          {% csrf_token %}
          <div class="input-group form-group mt-3">
            <input type="text" class="form-control text-center p-3" placeholder="Ingrese Codigo" name="apprentice" value="">
          </div>
          <!-- {{forms}} -->
          <button class="btn btn-primary mt-3">Grabar</button>
        </form>
        
        <!-- <form action="" method="post">

          <div class="input-group form-group mt-3">
            <input type="text" class="form-control text-center p-3" placeholder="Ingrese Codigo" name="id_code">
          </div>
          <div class="text-center">
            <input type="submit" value="Ingresar" class="btn btn-primary mt-3 w-100 p-2" name="login-btn">
          </div>
        </form> -->
      </div>
    <div class="card-footer p-3">
      <div class="d-flex justify-content-center">
        <div class="text-primary">If you are a registered user, login here.</div>
      </div>
    </div>
    </div>
  </div>
{% endblock content %}

student/templates/student/list.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}
  <script src="{% static '' %}" defer></script>
{% endblock scripts %}


{% block title %}
  {{title}}
{% endblock title %}


{% block content %}
  <h1 class="text-center">Lista de Horas</h1>
  <br>


  <h2>Lista de entrada y Salida</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">id_asst</th>
        <th scope="col">id_empleyo</th>
        <th scope="col">Nombres</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Hora de Entrada</th>
        <th scope="col">Hora de Salida</th>
        <th scope="col">Tiempo</th>
        <th scope="col">Proceso</th>
      </tr>
    </thead>
    <tbody>

    {% for a in ass %}
      <tr>
        {% if a.exit_boolean == False %}
        <td>{{a.id_ass}}</td>
        <td>{{a.apprentice.id_app}}</td>
        <td>{{a}}</td>
        <td>{{a.apprentice.surname}}</td>
        <td>{{a.entry_at|time:"H:i"}}</td>
         <td>--:--</td>
        <td>{{tiempo}}</td>
        <td><button type="submit" class="btn btn-warning" onclick="window.location='{% url 'student:summary_assitance' a.apprentice.id_app a.entry_at%}'">Salida</button></td>
        {% endif %}
      </tr>
    {% endfor %}

    </tbody>
  </table>

{% endblock content %}

student/templates/student/record.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}
  <script src="{% static '' %}" defer></script>
{% endblock scripts %}


{% block title %}
  {{title}}
{% endblock title %}


{% block content %}
  <h1 class="text-center">Lista de Horas</h1>
  <br>
  
  {% for s in obj %}
  <p>
    {{s.id_app}} - {{s.name}} - {{s.surname}} - {{s.created_at}} -{{s.updated_at}}
  </p>
  {% endfor %}
{{time}}
  <h2>Lista de entrada y Salida</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">id_persona</th>
        <th scope="col">Nombres</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Fecha Entrada</th>
        <th scope="col">Hora de Entrada</th>
        <th scope="col">Fecha de Salida</th>
        <th scope="col">Hora de Salida</th>
        <th scope="col">Tiempo</th>
        <th scope="col">Proceso</th>
      </tr>
    </thead>
    <tbody>
    {% for a, d in asst_time %}
      <tr>
          <td>{{a.id_ass}}</td>
          <td>{{a.apprentice.id_app}}</td>
          <td>{{a}}</td>
          <td>{{a.apprentice.surname}}</td>
          <td>{{a.entry_at|date}}</td>
          <td>{{a.entry_at|time:"H:i"}}</td>
          <td>{{a.exit_at|date}}</td>
          <td>{{a.exit_at|time:"H:i"}}</td>
          <td>{{ d }}</td>
          <td><button type="button" class="btn btn-danger">Imprimir</button> <button type="button" class="btn btn-info">Actualizar</button></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock content %}

student/templates/student/summary.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block css %}
<link rel="stylesheet" href="{% static '' %}">
{% endblock css %}
  

{% block scripts %}
  <script src="{% static '' %}" defer></script>
{% endblock scripts %}


{% block title %}
  {{title}}
{% endblock title %}


{% block content %}
  <h1 class="text-center">{{title}}</h1>
  <br>
  <form action="" method="POST">
    {% csrf_token %}
    <p name="id_asst">{{ass_id.id_ass}}</p>
    <p>{{ass_id.apprentice.name}}</p>
    <p>{{ass_id.entry_at}}</p>
    <p>{{ass_id.entry_boolean}}</p>
    <p>{{ass_id.exit_boolean}}</p>
    <button type="submit" class="btn btn-danger">Imprimir</button>
  </form>

  <br>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}
    {% endblock css %}

    <script src="{% static 'js/main.js' %}" defer></script>
    {% block scripts %}
    {% endblock scripts %}
      
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

{% endblock scripts %}


{% block title %}

{% endblock title %}
  

{% block content %}
<h1>ESTAMO EN INDEX</h1>

{% endblock content %}
  